import Head from "next/head";
import type { ReactNode } from "react";

/* eslint-disable-next-line */
export interface PageLayoutProps {
  children: ReactNode;
  title?: string;
}

const PageLayout = ({ children, title = "eziTodo" }: PageLayoutProps) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>{children}</div>
    </>
  );
};

export default PageLayout;
